version: 2
updates:
- package-ecosystem: npm
  directory: "/Source/Tailwind.Traders.Web/ClientApp"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-a11y-dialog
    versions:
    - 5.1.0
    - 5.1.1
    - 6.0.0
    - 6.1.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
- package-ecosystem: nuget
  directory: "/Source/Tailwind.Traders.Web"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: CsvHelper
    versions:
    - 24.0.0
    - 24.0.1
    - 25.0.0
    - 26.0.0
    - 26.0.1
    - 26.1.0
    - 27.0.0
    - 27.0.1
  - dependency-name: Azure.Storage.Blobs
    versions:
    - 12.8.1
  - dependency-name: MongoDB.Driver
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: Microsoft.AspNetCore.SpaServices.Extensions
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.HeaderPropagation
    versions:
    - 5.0.3
    - 5.0.4
